version: 0
identity: 'l8ngcMxHeB45aN'
secret: 'no1OCykNqdwiJZ'
lock: false
vote-expiration: 7
opt-out-usage: false
onvote:
  - cmd: tell %player Thanks for voting at %site!
    player-online: true
  - cmd: say Thanks for voting for us at %site, %player!
    player-online: false
votes: []
